config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'dashboard#home'
  get '/project_manager_dashboard' => 'dashboard#project_manager_dashboard'
  get '/developer_dashboard' => 'dashboard#developer_dashboard'

  root to: 'dashboard#home'

  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'log_in', to: 'devise/sessions#new'
    delete 'log_out', to: 'devise/sessions#destroy'
  end

  post '/dashboard/create_project' => 'dashboard#create_project'
  get  '/dashboard/get_developers' => 'dashboard#get_available_developers'
  post '/dashboard/save_project' => 'dashboard#save_project'
  post '/dashboard/save_todo_for_project' => 'dashboard#save_todo'
  post '/dashboard/assign_todo_dev' => 'dashboard#assign_todo_dev'
  get '/dashboard/get_todo_status' => 'dashboard#get_todo_status'
  post '/dashboard/change_todo_status' => 'dashboard#change_todo_status'

end

app/models/developer_todo.rb
class DeveloperTodo < ActiveRecord::Base
  belongs_to :user
  belongs_to :todo

  def self.add_todo(params)
  	params[:selected_dev_ids].each do |dev|
  		DeveloperTodo.find_or_create_by(user_id: dev , todo_id: params[:todo_id])
  	end
  end

  def self.get_all_assigned_developers_ids(todo_id)
  	DeveloperTodo.where("todo_id = ?", todo_id).pluck(:user_id).to_a
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :users, through: :project_developers
	has_many :todos

	def self.save_project(title)
		new_project = Project.new()
		new_project.name = title
		new_project.save!
		new_project.id
	end

end

app/models/project_developer.rb
class ProjectDeveloper < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  def self.get_all_assigned_developers_ids(project_id)
  	ProjectDeveloper.where("project_id = ?", project_id).to_a.uniq
  end

  def self.assign_dev_to_project(project_id, selected_dev_ids)
  	selected_dev_ids.each do |dev_id|
  		ProjectDeveloper.create(project_id: project_id, user_id: dev_id)
  	end	
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :project
	has_many :users, through: :developer_todos

	def self.create_todo(project_id, todo_list_arr)
		todo_list_arr.each do |dev_id|
  			Todo.create(project_id: project_id, item: dev_id)
  		end	
	end

	def self.get_status(todo_id)
		Todo.where("id = ?", todo_id)
	end

	def self.change_status(params)
		todo = Todo.find_by_id(params[:todo_id])
		todo.update_attributes(:status => params[:status])
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	has_many :projects, through: :project_developers
	has_many :todos, through: :developer_todos

	def self.get_all_developers
		User.all.where("role = ?", 2)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :role, :email, :password, :password_confirmation) }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'gchart'

	before_action :verify_as_manager, except: [:home, :developer_dashboard, :get_todo_status, :change_todo_status] 
	before_action :verify_as_developer, except: [:home, :assign_todo_dev, :save_todo, :add_project, :project_manager_dashboard, :create_project, :save_project, :get_available_developers] 

  def home
  	begin
  		redirect_path = current_user.role == 1 ? "/project_manager_dashboard" : "/developer_dashboard"
  		redirect_to redirect_path
  	rescue Exception => e
  		Rails.logger.error "message: #{e.message}"
  	end
  end

  def project_manager_dashboard
  	begin
      @line_chart  = GenerateChart.generate_pie_chart
  	rescue Exception => e
  		Rails.logger.error "message: #{e.message}"
  	end
  end

  def developer_dashboard
  	begin
  		
  	rescue Exception => e
  		Rails.logger.error "message: #{e.message}"
  	end
  end

  def create_project
  end

  def save_project
    begin
      project_id = Project.save_project(params[:project_name])
      ProjectDeveloper.assign_dev_to_project(project_id, params[:selected_dev_ids]) if (!params[:selected_dev_ids].blank?)
      Todo.create_todo(project_id,params[:todo_list]) if (!params[:todo_list].blank?)
      redirect_to "/home"
    rescue Exception => e
      Rails.logger.error "message: #{e.message}"
    end
  end

  def get_available_developers()
    begin 
      @developers = User.get_all_developers
      @assigned_developers = params[:project_status] == "create" ? [] : DeveloperTodo.get_all_assigned_developers_ids(params[:todo_id])
    rescue Exception => e
      Rails.logger.error "message: #{e.message}"
    end
  end

  def add_project
  end

  def save_todo
    Todo.create_todo(params[:project_id], params[:todo_list]) if (!params[:todo_list].blank?)
    redirect_to "/home"
  end

  def assign_todo_dev
    DeveloperTodo.add_todo(params)
    redirect_to "/home"
  end

  def get_todo_status
    @status = Todo.get_status(params[:todo_id])
  end

  def change_todo_status
    Todo.change_status(params)
    redirect_to "/home"
  end

  protected

  def verify_as_manager
  	if current_user.role != 1
  		redirect_to "/home"
  	end
  end

  def verify_as_developer
  	if current_user.role != 2
  		redirect_to "/home"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_add_developer.html.erb
Select Developers:
<br />

<% developers.each do  |developer| %>

	<%if assign_devs.include? developer.id  %>
		<input type="checkbox" class="dev_checkbox" value="<%= developer.id %>" checked="checked""><%= developer.first_name %><br>
	<%else%>
		<input type="checkbox" class="dev_checkbox" value="<%= developer.id %>"><%= developer.first_name %><br>
	<%end%>
<% end %>
<input type ="hidden" name="developers" value="" id="checked_dev">
<%if type=="edit"%>
	<button type="save" value="Save" id="save_add_dev_block" onclick="save_add_dev_block_pr(this,<%=todoId%>);" >Save</button>
	<button type="reset" value="Reset" id="cancel_add_dev_block_pr<%=todoId%>" onclick="cancel_add_dev_block_pr(this,<%=todoId%>);" >Cancel</button>
<%else%>
	<button type="reset" value="Reset" id="cancel_add_dev_block">Cancel</button>
<%end%>

app/views/dashboard/_add_project.html.erb
<div id="add_project_popup" title="Add Project" style=""; class="confirmation">
	<form data-remote="true" action="/dashboard/save_project" method="post" id="add_project_popup_form">
		<!-- <div class="confirmationmsg" id="setDefaultGroupConfirmationMessage">			
		</div> -->
		<div class="bottombtn">
		Title: <input type="text" name="project_name" id="project_name" required><br>
		<br />
		<input type="button" value="Add Developer" name="" id="add_developer_btn" onclick="openDeveloperForm(this, 'create');">
		
		<div id="add_dev_block" class="add_dev_block" hidden></div>
		<br />
		<br />
		<input type="button" value="Add Todo" name="" id="add_todo_btn" onclick="openTodoForm(this);">
		<div id="add_todo_block" class="add_todo_block" hidden></div>
		<br />
		<br />
		<div class="bottombtn">
			<input type="submit" name="" value="Save" class="save_project_btn" id="add-project-save-btn">
			<input type="button" value="Cancel" class="cancel" name="" id="add_project_cancel_btn" onclick="closeCreateProjectPopup(this);">
		</div>

	</form>
</div>

app/views/dashboard/_change_status.html.erb
<div id ="radio_option<%=todoId%>" class="radio_option">
	<input type="radio" name="stat" value="new"> new<br>
	<input type="radio" name="stat" value="in progress"> In Progress<br>
	<input type="radio" name="stat" value="done"> Done<br>
	<div class="bottombtn">
		<input type="submit" name="" value="Save" class="save_status_btn" id="save_status_btn<%=todoId%>" onclick="save_change_status(this,<%=todoId%>);">
		<button type="reset" value="Reset" id="cancel_status<%=todoId%>" onclick="cancel_change_status(this,<%=todoId%>);">Cancel</button>
	</div>
</div>

app/views/dashboard/create_project.js.erb
$("#create-project-btn").hide();
$("#add_project_form").empty().append("<%= escape_javascript(render(:partial=>'dashboard/add_project')); %>");

app/views/dashboard/developer_dashboard.html.erb
<script type="text/javascript">
	var current_user_id ='<%=current_user.id %>';
</script>
<div id = "logout-button">
	<%= form_tag( log_out_url, method: :delete ) %>
	<%= submit_tag "Sign out" %>
</div>

<% my_todo_list = DeveloperTodo.where("user_id = ?", current_user.id).pluck(:todo_id).to_a %>
<% todo_list = Todo.where("id IN (?)", my_todo_list) %>


<div id ="see_all_todo" class="see_all_todo">                
    <b>My Todos</b><br \><br \>
    <div id ="todo_dev" class="todo_dev">
	    <% todo_list.each do |todo| %>
	    	<div id ="see_my_todos<%=todo.id%>" class="see_my_todos">
	    		<b>-> <%= todo.item %> </b> &ensp; <b> <%= todo.status %> </b> &ensp; <input type="button" value="Change Status" name="" id="change_status_btn_for_todo<%= todo.id %>" onclick="openChangeStatusOption(this,<%= todo.id%>);">
				<div id="add_change_status_block<%= todo.id %>" class="add_change_stat_block_pr" hidden></div>   <br \><br \>
			</div>
	    <%end%>
    </div>
</div>

app/views/dashboard/get_available_developers.js.erb
var projectId = '<%= params[:project_id] %>';
var todoId = '<%= params[:todo_id]%>';
<% if params[:project_status] == "create" %>
	$("#add_dev_block").empty().append("<%= escape_javascript(render(:partial=>'dashboard/add_developer', :locals => {:developers => @developers, :type => "create", :assign_devs => []})); %>");
	$("#add_dev_block").show();
<%else%>
	$("#add_dev_block_pr"+todoId).empty().append("<%= escape_javascript(render(:partial=>'dashboard/add_developer', :locals => {:developers => @developers, :assign_devs => @assigned_developers, :type => "edit", :todoId => params[:todo_id]})); %>");
	$("#add_dev_block_pr"+todoId).show();
<%end%>

app/views/dashboard/get_todo_status.js.erb
var todoId= '<%=params[:todo_id]%>'
$("#change_status_btn_for_todo"+todoId).hide();
$("#add_change_status_block"+todoId).show();
$("#add_change_status_block"+todoId).empty().append("<%= escape_javascript(render(:partial=>'dashboard/change_status', :locals => {status: @status, todoId: params[:todo_id]})); %>");

app/views/dashboard/home.html.erb
<h1>Dashboard#home</h1>
<p>Find me in app/views/dashboard/home.html.erb</p>

app/views/dashboard/project_manager_dashboard.html.erb
<div id ="project_manager_dashboard_form">

	


	<div id = "logout-button">
		<%= form_tag( log_out_url, method: :delete ) %>
		<%= submit_tag "Sign out" %>
	</div>

	<div class="btnrow create-project">                
	    <input type="button" class="create-project" name="" value="Create Project" id="create-project-btn">
	</div>
	
	<div id="add_project_form">
	</div>
	<div id ="add_todo_form">
	</div>

	<br \>
	<b>Project Status</b>
	<br></br>
	<% all_projects = Project.all %>
	<% if !all_projects.empty? %>
		<div class= "project_status_block">
		<% all_projects.each do |project| %>
				<b>-> <%= project.name%></b> <input type="button" value="Add Todo" name="" id="add_todo_btn_for_project<%= project.id%>" onclick="openTodoFormForProject(this,<%= project.id%>);"><br></br>
				<div id="add_todo_block_pr<%= project.id%>" class="add_todo_block_pr" hidden></div>
		<%end%>
		</div>
	<% end %>
	<br \>
	<b>Assign Todo</b>
	<br></br>
	<% all_todos = Todo.all %>
	<% all_developers = User.where("role = ?", 2) %>
	<% if !all_todos.empty? %>
		<div class= "assign_todo_block">
		<% all_todos.each do |todo| %>
				<b>-> <%= todo.item%></b> <input type="button" value="Add Developer" name="" id="add_dev_btn_for_todo<%= todo.id %>" onclick="openAddDevFormForProject(this,<%= todo.id%>, <%= todo.project_id %>);"><br></br>
				<div id="add_dev_block_pr<%= todo.id %>" class="add_dev_block_pr" hidden></div>
		<%end%>
		</div>
	<% end %>

	<br \>
	<b>Developer Status</b> 
		<br></br>
		<% users = User.where("role= ?", 2) %>
		<table width="100%" border="1" cellspacing="0" cellpadding="0" align="center">
			<colgroup>
			<col style="width: 15%;">
			<%users.each do |user|%>
	        	<col style="width: 13%;">
         	<%end%>
	        </colgroup>
			<tr align="center">
				<th class="table-heading border-right-none">Status</th>
				<%users.each do |user|%>
	        		<th class="table-heading border-right-none"><%= user.first_name %> </th>
         		<%end%>
				
			</tr>

				<tr>
					<th class="table-heading border-right-none">New</th>
					<%users.each do |user|%>
						<% tot =[]%>
						<% todos = DeveloperTodo.where("user_id= ?",user.id).pluck(:todo_id).to_a %>
						<% new_todo = Todo.where("status = ? and id IN (?)", "new", todos) %>
						<%count = new_todo.count%>
						<% new_todo.each do |todo|%>
							<% tot << todo.item %>
						<%end%>
						<th class="table-heading border-right-none" ><%= tot.join(",") %></th>
					<%end%>
				<!-- add  new todos for first developer -->
				</tr>

				<tr>
					<th class="table-heading border-right-none">In progress</th>
					<%users.each do |user|%>
						<% tot =[]%>
						<% todos = DeveloperTodo.where("user_id= ?",user.id).pluck(:todo_id).to_a %>
						<% new_todo = Todo.where("status = ? and id IN (?)", "in progress", todos) %>
						<%count = new_todo.count%>
						<% new_todo.each do |todo|%>
							<% tot << todo.item %>
						<%end%>
						<th class="table-heading border-right-none" ><%= tot.join(",") %></th>
					<%end%>
					
				</tr>

				<tr>
					<th class="table-heading border-right-none">Done</th>
					<%users.each do |user|%>
						<% tot =[]%>
						<% todos = DeveloperTodo.where("user_id= ?",user.id).pluck(:todo_id).to_a %>
						<% new_todo = Todo.where("status = ? and id IN (?)", "done", todos) %>
						<%count = new_todo.count%>
						<% new_todo.each do |todo|%>
							<% tot << todo.item %>
						<%end%>
						<th class="table-heading border-right-none" ><%= tot.join(",") %></th>
					<%end%>

				</tr>
				

		</table>

<br />
<div class = "pie-chart">
	<b>Todo status Project-Wise</b><br />
		<%@line_chart.each do |line|%>
			<%= image_tag(line) %>
		<%end%>
	</div>
	

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="main">
<div class="page">
<div class="header">
<h1>TODO</h1>
</div>
<div class="topmenu">
<ul>
  <li style="background: transparent none repeat scroll 0% 50%; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; padding-left: 0px;"><a href="#">Home</a></li>
  <li><a href="#">About Us</a></li>
  <li><a href="#">Recent articles</a></li>
  <li><a href="#">Email</a></li>
  <li><a href="#">Resources</a></li>
  <li><a href="#">Links</a></li>
</ul>
</div>
<div class="content">
	<div class="left-panel">
		<div class="left-panel-in">
			<%= yield %>
		</div>
	</div>
</div>

<div class="footer">

</div>

</div>
</div>

</body>
</html>